name: Build VBA

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Setup VBA Runtime"
        uses: DecimalTurn/setup-vba@abad6bed4025d3d709cbd9c9281f856d298bd68d # v0.1.2
        with:
          office-apps: "Excel,Word,PowerPoint"
          install-office: "true"
      - name: "Build VBA-Enabled Documents"
        id: build_vba
        uses: DecimalTurn/VBA-Build@73d88e15e27d1e80aa402c60981175a491281d25 # v2.0.0
        with:
          source-dir: "./src"
        timeout-minutes: 20
      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v4
        id: "upload"
        with:
          name: "VBA-Enabled-Documents"
          path: "./src/out/*"
          if-no-files-found: warn
      - name: "Attestation"
        if: ${{ !github.event.repository.private }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: "VBA-Enabled-Documents"
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}







