name: XLS to XLSM

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'input/**'

permissions:
  contents: read

jobs:
  convert:
    runs-on: windows-2025
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Setup VBA Runtime"
        uses: DecimalTurn/setup-vba@abad6bed4025d3d709cbd9c9281f856d298bd68d # v0.1.2
        with:
          office-apps: "Excel"
          install-office: "true"
      - name: "Convert XLS to XLSM"
        shell: pwsh
        run: |
          ./scripts/Convert-XlsToXlsm.ps1 -InputDir "./input" -OutputDir "./output"
      - name: "Upload Converted Files"
        uses: actions/upload-artifact@v4
        with:
          name: "XLSM-Files"
          path: "./output/*.xlsm"
          if-no-files-found: warn







